services:

  temporal:
    image: temporalio/auto-setup:1.28.0
    hostname: temporal
    networks:
      - reddit-post-notifier
    depends_on:
      mysql:
        condition: service_started
    environment:
      DB: mysql8
      DBNAME: temporal
      VISIBILITY_DBNAME: temporal_visibility
      DB_PORT: 3306
      MYSQL_SEEDS: mysql
      MYSQL_USER: root
      MYSQL_PWD: root
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233
      DEFAULT_NAMESPACE: reddit-post-notifier
      DEFAULT_NAMESPACE_RETENTION: 7d
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      LOG_LEVEL: error
    volumes:
      - ./deployments/docker/temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
    healthcheck:
      test: CMD-SHELL tctl --address temporal:7233 workflow list
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 5s
    ports:
      - '7233:7233'

  temporal-ui:
    image: temporalio/ui:v2.38.3
    hostname: temporal-ui
    networks:
      - reddit-post-notifier
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_HIDE_LOGS: true
    ports:
      - '8181:8080'

  mysql:
    image: mysql:8.4.5
    hostname: mysql
    networks:
      - reddit-post-notifier
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql-data:

networks:
  reddit-post-notifier:
    driver: bridge
