services:

  temporal:
    image: temporalio/auto-setup:1.27.2
    hostname: temporal
    networks:
      - reddit-post-notifier
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB: postgres12
      DBNAME: temporal
      VISIBILITY_DBNAME: temporal_visibility
      DB_PORT: 3306
      POSTGRES_SEEDS: mysql
      POSTGRES_USER: root
      POSTGRES_PWD: root
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233
      DEFAULT_NAMESPACE: reddit-post-notifier
      DEFAULT_NAMESPACE_RETENTION: 7d
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      LOG_LEVEL: error
    volumes:
      - ./deployments/docker/temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
    healthcheck:
      test: CMD-SHELL tctl --address temporal:7233 workflow list
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 5s
    ports:
      - '7233:7233'

  temporal-ui:
    image: temporalio/ui:v2.37.3
    hostname: temporal-ui
    networks:
      - reddit-post-notifier
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_HIDE_LOGS: true
    ports:
      - '8181:8080'

  mysql:
    image: mariadb:11.8.2-ubi9
    hostname: mysql
    networks:
      - reddit-post-notifier
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'