#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    CREATE USER $RPN_DB_USER WITH PASSWORD '$RPN_DB_PWD';
    CREATE DATABASE $RPN_DB_DBNAME OWNER $RPN_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$RPN_DB_DBNAME" <<-EOSQL
    -- 1. Grant access to the schema
    GRANT ALL PRIVILEGES ON SCHEMA public TO $RPN_DB_USER;

    -- 2. Grant access to all EXISTING tables, sequences, and functions
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $RPN_DB_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $RPN_DB_USER;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $RPN_DB_USER;

    -- 3. Ensure FUTURE tables created by migrations also grant access to the RPN user
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $RPN_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $RPN_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO $RPN_DB_USER;
EOSQL